name: Add TSV File

on:
  workflow_dispatch:

jobs:
  add-tsv-file:
    runs-on: self-hosted  # Ensure your self-hosted runner is used
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List LENOVO Directory Contents
        run: |
          Get-ChildItem "C:\Users\Aravind.kumar\Documents\Batch_files\LENOVO"
      
      - name: Copy TSV file to repository directory
        run: |
          # Ensure the file exists before copying
          if (Test-Path "C:\Users\Aravind.kumar\Documents\Batch_files\LENOVO\lenovo_kr_mandatory_test.tsv") {
              Copy-Item "C:\Users\Aravind.kumar\Documents\Batch_files\LENOVO\lenovo_kr_mandatory_test.tsv" "$env:GITHUB_WORKSPACE\"
          } else {
              Write-Error "File not found: C:\Users\Aravind.kumar\Documents\Batch_files\LENOVO\lenovo_kr_mandatory_test.tsv"
          }

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push TSV file
        run: |
          git add lenovo_kr_mandatory_test.tsv
          git commit -m "Add lenovo_kr_mandatory_test.tsv file"
          git push origin main
