name: Update TSV file from local LENOVO feed

on:
  schedule:
    - cron: '5 23 * * *'   # Runs daily at 11:05 PM UTC / 8:05 AM KST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-file:
    runs-on: [self-hosted, windows]  # This job must run on a self-hosted Windows runner

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Copy new file from local path
        run: |
          copy "C:\Users\Aravind.kumar\Documents\Batch files\LENOVO\lenovo_kr_mandatory_test.tsv" test_file.txt
        shell: cmd

      - name: Commit changes
        shell: pwsh
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add test_file.txt
          
          # Check if there are any changes to commit
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
            git commit -m "Update test_file.txt from local LENOVO feed"
            git push
          } else {
            Write-Host "No changes to commit."
          }
