name: Add TSV File

on:
  workflow_dispatch:

jobs:
  add-tsv-file:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy TSV file to repository directory
        run: |
          # Copy the file from the absolute path to the current workspace folder
          Copy-Item "C:\Users\Aravind.kumar\Documents\Batch files\LENOVO\lenovo_kr_mandatory_test.tsv" "$env:GITHUB_WORKSPACE\"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push TSV file
        run: |
          git add lenovo_kr_mandatory_test.tsv
          git commit -m "Add lenovo_kr_mandatory_test.tsv file"
          git push origin main
