name: Update TSV file from Lenovo feed

on:
  schedule:
    - cron: '5 23 * * *'   # Runs daily at 11:05 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-file:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        
      - name: Download new file
        run: |
          curl -v -u "${{ secrets.FEED_USERNAME }}:${{ secrets.FEED_PASSWORD }}" \
               -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
               -o test_file.txt \
               "https://luezen5ed3.execute-api.eu-west-1.amazonaws.com/datasets-https/lenovo/301257/lenovo_kr_mandatory_test.tsv"

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add test_file.txt
          
          if ! git diff --cached --quiet; then
            git commit -m "Update test_file.txt from Lenovo feed"
            git push
          else
            echo "No changes to commit."
          fi
